### ISSUE TITLE
您好，不好意思打扰您了，请问论文MCANet: Medical Image Segmentation with Multi-Scale Cross-Axis Attention中的Multi-scale Cross-axis Attention (MCA)代码实现在哪里呀

### ISSUE THREAD

**Issue by wjrcs** [haoshao-nku/medical_seg#11]

**Comment by liuwanqingqing** [comment]
你好，请问您有找到吗，我也在找这段代码。如果有找到可以分享一下吗，感谢，祝好。

**Comment by wjrcs** [comment]
我记得我当时好像是找到了，这是四月份的事情了，我也不太记得了，那个作者公布的代码挺多的，可以尝试再找找看，因为我都是直接找代码拼接到我的baseline上的，所以我这没有代码保存



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年10月19日(周六) 中午11:22
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [haoshao-nku/medical_seg] 您好，不好意思打扰您了，请问论文MCANet: Medical Image Segmentation with Multi-Scale Cross-Axis Attention中的Multi-scale Cross-axis Attention (MCA)代码实现在哪里呀 (Issue #11)




 
你好，请问您有找到吗，我也在找这段代码。如果有找到可以分享一下吗，感谢，祝好。
