### ISSUE TITLE
Question: image size in a custom dataset

### ISSUE THREAD

**Issue by aimanmutasem** [haoshao-nku/medical_seg#16]
Thank you for your great work! 

I'm trying to implement MCANet for a custom dataset. Is there are any recommended instructions? Do I have to reset the size of the image in the code? I use image size 1024 by 768 in my dataset.

**Comment by haoshao-nku** [comment]
Thanks for your attention.  According to our experiments, the image size does not have a big impact on the results. We use 224*224 on the synapse dataset and 512*512 on other datasets.

**Comment by aimanmutasem** [comment]
Thank you for your reply; : ) 
This means I don't have to change anything in the code and upload the data as it is, right?
