### ISSUE TITLE
Hello, how can  I run this project? I can't find train.py.

### ISSUE THREAD

**Issue by yike5022** [haoshao-nku/medical_seg#9]

**Comment by haoshao-nku** [comment]
Training, testing and other details about "Polyper: Boundary Sensitive Polyp Segmentation" can be found at /medical_seg/mmsegmentation/local_config/ Polyper-AAAI2024/readme.md.


Training, testing, and other details about "MCANet: Medical Image Segmentation with Multi-Scale Cross-Axis Attention" can be found at /medical_seg/ mmsegmentation/local_config/MCANet/readme.md.
